### PR TITLE
Add welcoming prompt

### LINKED ISSUE #7: 7. As a user, I want to see a welcoming prompt to add my first item if my list is empty to help me get oriented to how the app works.
## Summary

When a user starts a new list, they need a little guidance on how to get started. Think through what you'd want to see as a user and make some intentional user experience decisions that will guide our users in confidently adding their very first item. 

## Acceptance criteria
- [x] The list view, when there are no items to display, should show a prompt (e.g., a button) for the user to add their first item

## Notes
- [The wireframe](https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/list-empty.png) is a little short on the "welcoming" part of the story, but otherwise is functionally complete for the purposes of the AC.

### PR DESCRIPTION
**Pull request by ToobaJamal**
Co-authored-by: l.abrocadabro@gmail.com

## Description

This change adds a welcoming prompt on the List page. If the user goes to the List page with no list token saved in local storage, an Add item button is displayed on the screen. Clicking on the Add item button takes the user to the `add-item` page.

## Related Issue

Closes #7  

## Acceptance Criteria

- [x] The list view, when there are no items to display, should show a prompt (e.g., a button) for the user to add their first item

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

https://user-images.githubusercontent.com/52610124/234607427-9a662709-7ca9-49ab-99d4-4126d75d233e.mp4

### After

https://user-images.githubusercontent.com/52610124/234607607-c466f569-8545-4dfb-bd6c-623add5b3a68.mp4

## Testing Steps / QA Criteria

1. Run `git checkout tj-la-new-list-welcome-message`
2. Run `npm start`
3. Verify if the List page shows an Add item button which takes you to the `add-item` page when there is no saved list in your browser

### CODE REVIEW

**Comment by RajGM** [comment]
Hi, @ToobaJamal and @labrocadabro 
The prompt is not showing up in the preview link.

**Comment by ToobaJamal** [comment]
> Hi, @ToobaJamal and @labrocadabro The prompt is not showing up in the preview link.

Hi Raj,

I just checked it and its working on my browser. @labrocadabro, could you please confirm?

https://user-images.githubusercontent.com/52610124/234956992-6d379fd5-7916-4fcf-97b9-f13817062f15.mp4

**Comment by labrocadabro** [comment]
I also checked from the preview link and it seems to be fine.


https://user-images.githubusercontent.com/5794319/235034269-11b670ab-3eb9-4b88-8570-7da7b0ca08e4.mov

**Comment by RajGM** [comment]
Working on mine as well.

**Review by paramsiddharth — APPROVED** [review]
Good work, Tooba and Laura! :)

**Review by paramsiddharth — APPROVED** [review]

**Review by paramsiddharth — APPROVED** [review]

**Pull request merged**
