### PR TITLE
Responsive Design

### LINKED ISSUE #45: As a user, I want to access my list on any device of my choosing
Make sure the app is responsive. It should both display and function correctly on phones and other mobile devices, along with larger-resolution displays.

- [ ] The app should function correctly on any screen width of 300px or larger.
- [ ] There should be no display bugs (overlapping or displaced elements, for example).
- ~~A loading state should be implemented so users on slow connections are not presented with a blank page and no feedback.~~

Note: the loading state requirement was removed. When I tested the site on a throttled connection, it simply showed a completely blank white page until the entire app suddenly loaded, and the loader was only displayed for a fraction of a second.

### PR DESCRIPTION
**Pull request by labrocadabro**
## Description

This PR implements some minor styling changes to accommodate small screens.

## Related Issue

Closes #45

## Acceptance Criteria

- [x] The app should function correctly on any screen width of 300px or larger.
- [x] There should be no display bugs (overlapping or displaced elements, for example).

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓   | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

Home page before responsive
Empty list page before responsive

List page with items, before responsive

### After

Screen Shot 2023-05-26 at 3 02 53 PM
Screen Shot 2023-05-26 at 3 02 43 PM
Screen Shot 2023-05-26 at 3 02 33 PM

## Testing Steps / QA Criteria

View the app at a very small screen width (300-400px).

### CODE REVIEW

**Comment by RajGM** [comment]
tcl-1
The title jumps little early

**Comment by RajGM** [comment]
tcl-2
A minor edge case

**Comment by labrocadabro** [comment]
> tcl-2 A minor edge case

Since the smallest screen width in common use is 320px, I didn't bother supporting resolutions below 300.

**Comment by labrocadabro** [comment]
> The title jumps little early

I think you mean it's left-aligned at resolutions where it should be centered? If yes, I've fixed it. :)

**Review by shahx95 — APPROVED** [review]

**Review by shagunZ — APPROVED** [review]

**Review by ToobaJamal — APPROVED** [review]

**Review by paramsiddharth — APPROVED** [review]
Looks good! :)

**Review by RajGM — APPROVED** [review]

**Pull request merged**
