### PR TITLE
Added navigation support

### LINKED ISSUE #2: 2. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [ ] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouterdotcom.fly.dev/docs/en/v6/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

### PR DESCRIPTION
**Pull request by shahx95**
Co-authored-by: shagunmengi003@gmail.com

## Description

In the Layout component, NavLink was imported from React Router DOM. The previously used anchor links within the nav element were replaced with NavLinks, which direct to the "Home", "List", and "Add item" pages.

## Related Issue
Closes #2 

## Acceptance Criteria

- The nav element is added to the Layout component
- Links to the "Home", "List", and "Add item" pages of the app are In the nav element
- The links all function as expected using the NavLink component from react-router-dom

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

```
import { Outlet } from 'react-router-dom';

<nav className="Nav">
					<a href="#" className="Nav-link">
						Home
					</a>
					<a href="#" className="Nav-link">
						List
					</a>
                                        <a href="#" className="Nav-link">
						 Add Item
				        </a>
</nav>
```

### After
```
import { Outlet, NavLink } from 'react-router-dom';

<nav className="Nav">
					<NavLink to="/" className="Nav-link">
						Home
					</NavLink>
					<NavLink to="/list" className="Nav-link">
						List
					</NavLink>
					<NavLink to="/add-item" className="Nav-link">
						Add Item
					</NavLink>
</nav>
```

## Testing Steps / QA Criteria

Click on the links in the nav and ensure they lead to the correct pages.

### CODE REVIEW

**Comment by labrocadabro** [comment]
Look great! 👍  Only recommendation I would make is to remove the TODO comment.

**Review by ToobaJamal — COMMENTED** [review]
Looks good to me 😊

**Comment by shahx95** [comment]
> Look great! 👍 Only recommendation I would make is to remove the TODO comment.

Removed the TODO comment. Thanks for the suggestion. 😊

**Review by paramsiddharth — APPROVED** [review]
Good work, @shahx95 and @shagunZ ! :)

**Review by labrocadabro — APPROVED** [review]
👍

**Comment by RajGM** [comment]
Great work @shahx95 and @shagunZ 
LGTM, let's test it out during the demo.

**Review by RajGM — APPROVED** [review]

**Pull request merged**
