### PR TITLE
Implement switch list using useNavigate

### PR DESCRIPTION
**Pull request by shahx95**
Draft PR to discuss an alternative implementation for Switch List

### CODE REVIEW

**Comment by shahx95** [comment]
Problem:
When I click on Switch List, it clears the local storage but redirects to "/list" instead of "/"

**Comment by RajGM** [comment]
> Problem: When I click on Switch List, it clears the local storage but redirects to "/list" instead of "/"

Even when I click on Home it's redirecting to /list not to /

**Comment by RajGM** [comment]
Main trouble is / is being redirected to /list

**Comment by shahx95** [comment]
# Solution to the aforementioned problem: 

Previously, the token was being manually removed from localStorage instead of utilizing setListToken(). This caused a mismatch between the localStorage and the component state. Consequently, when `switch list` was clicked, the token was removed from localStorage, but it still existed in listToken state. As a result, we saw a redirection to /list as per the homepage logic.

The problem has been addressed by creating a clearListToken function in the app which sets listToken to null. The clearListToken runs when `switch list` is clicked. By doing so, we resolve the discrepancy and ensure proper redirection to the homepage.

**Comment by labrocadabro** [comment]
Screen Shot 2023-05-27 at 6 31 16 PM
We've got an extra switch list link

**Comment by shahx95** [comment]
> Screen Shot 2023-05-27 at 6 31 16 PM We've got an extra switch list link

Thanks. Taken care of.

**Review by labrocadabro — APPROVED** [review]
Looks good!

**Review by RajGM — APPROVED** [review]

**Pull request merged**
